{
"ada": {"author_nick": "carlo", "author_name": "Carlo Emmanoel", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"eva": {"author_nick": "pud-19-03", "author_name": "Cibele Ribeiro", "author_email": "cibele@nce.ufrj.br", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"henrietta": {"author_nick": "fono-games", "author_name": "Games Inteligentes e Fonoaudiologia Computacional", "author_email": "labasence@gmail.com", "author_org": "LABASE-FONOCOMP", "author_site": "http://www.superpython.net", "author_public": "on"},
"soraya": {"author_nick": "carlo", "author_name": "Carlo Oliveira", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "", "author_public": "on"},
"henrietta": {"author_nick": "brunafiuza", "author_name": "Bruna Fiuza", "author_email": "brunafiuza@live.com", "author_org": "", "author_site": "", "author_public": "on"},
"margaret": {"author_nick": "fonocomp1_19", "author_name": "FonoComp I 2019", "author_email": "carlo@nce.ufrj.br", "author_org": "UFRJ", "author_site": "http://labase.nce.ufrj.br", "author_public": "on"},
"mary_shaw": {"author_nick": "POO PPGI 19.3", "author_name": "Labase - Disciplina de ProgramaÃ§Ã£o Orientada a Objetos - PPGI 2019-3", "author_email": "carlo@ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"vera": {"author_nick": "fonocomp_II_19", "author_name": "Fonocomp II 2019", "author_email": "hello@ub.br", "author_org": "", "author_site": "", "author_public": "on"},
"gertrude": {"author_nick": "fonocomp_II_18", "author_name": "Fonocomp II 2018", "author_email": "hello@ub.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"grace": {"author_nick": "dev_agl_22_II", "author_name": "Dev Agl 2022 II", "author_email": "hello@ub.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"betty": {"author_nick": "fonocomp_I_18", "author_name": "Fonocomp I 2018", "author_email": "hello@ub.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"anita": {"author_nick": "SupyGirls_D_Piza", "author_name": "SupyGirls D. Piza", "author_email": "hello@ub.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"karen": {"author_nick": "CDERJ_Hortência", "author_name": "CEDERJ Students oriented by Isabel Hortência", "author_email": "hortencia.garnica@nce.ufrj.br", "author_org": "CDERJ", "author_site": "https://www.cecierj.edu.br", "author_public": "on"},
"irene": {"author_nick": "JAIE_2019", "author_name": "Oficina JAIE 2019", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"kathleen": {"author_nick": "ZENOBIO_2019", "author_name": "Genetica Zenóbio 2019", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"lorinda": {"author_nick": "PIBIC_EM_2020", "author_name": "Pibic-EM Zenóbio 2020", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"hedy": {"author_nick": "PIBIC_2022", "author_name": "Pibic Daniel Piza 2022", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"sophie": {"author_nick": "GamesDP_2021", "author_name": "SuperPython LABASE 2021", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"patricia": {"author_nick": "PPGI_OO_2020", "author_name": "Curso Desenvolvimento PPGI 2020", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"janese": {"author_nick": "UNESP_2020", "author_name": "Curso Extensão UNESP 2020", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"roberta": {"author_nick": "Python_2020", "author_name": "Curso Iniciação Python 2020", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"phyllis": {"author_nick": "WorkShop_2020", "author_name": "Workshop SupyGirls Outubro 20202", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"elizabeth": {"author_nick": "WorkShop_2020", "author_name": "Workshop SupyGirls Outubro 20202", "author_email": "carlo@nce.ufrj.br", "author_org": "LABASE", "author_site": "labase.nce.ufrj.br", "author_public": "on"},
"joanna": {"author_nick": "bellexand", "author_name": "isabelle alexandre da silva", "author_email": "isabellesilva031@gmail.com", "author_org": "", "author_site": "", "author_public": "on"},
"grete": {"author_nick": "ST_Agora_18", "author_name": "ST_Agora_18", "author_email": "akakaka@gmail.com", "author_org": "Agora", "author_site": "http://colegioagoraniteroi.com.br/", "author_public": "on"},
"megan": {"author_nick": "katia", "author_name": "Katia Guimarães Sousa Palomo", "author_email": "profa.katia.palomo@gmail.com", "author_org": "Instituto Federal de Brasília", "author_site": "www.ifb.edu.br", "author_public": "on"},
"joan": {"author_nick": "STEAM_CL", "author_name": "STEAM_CL", "author_email": "cici.rco@gmail.com", "author_org": "", "author_site": "", "author_public": "on"},
"radia": {"author_nick": "NEW_00", "author_name": "NEW_00", "author_email": "", "author_org": "", "author_site": "", "author_public": "on"},
"irma": {"author_nick": "NEW_01", "author_name": "NEW_01", "author_email": "", "author_org": "", "author_site": "", "author_public": "on"},
"monica": {"author_nick": "NEW_02", "author_name": "NEW_02", "author_email": "", "author_org": "", "author_site": "", "author_public": "on"},
